In [6]:
import numpy as np

vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
import numpy as np

vector = np.zeros((3, 3), dtype=int)
print(vector)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
import numpy as np


matrix = np.random.randint(1, 11, size=(5, 5))
print(matrix)

[[9 9 5 7 2]
 [4 7 8 7 9]
 [3 1 1 3 3]
 [2 9 6 4 6]
 [2 7 1 1 3]]


In [15]:
import numpy as np

random_matrix_float = np.random.rand(4, 4)
print(random_matrix_float)


[[0.41304988 0.14703933 0.05601426 0.75019095]
 [0.84589318 0.77085555 0.28600752 0.69298761]
 [0.71788009 0.23438972 0.2625569  0.79022482]
 [0.5544625  0.79447719 0.76152584 0.02822884]]


In [18]:
import numpy as np

array_1 = np.random.randint(1, 11, size=(5))
array_2 = np.random.randint(1, 11, size=(5))

opperation_1 = array_1 + array_2
opperation_2 = array_1 - array_2
opperation_3 = array_1 * array_2

print(array_1, array_2)
print(opperation_1)
print(opperation_2)
print(opperation_3)

[ 9  4  4  5 10] [ 6  5  6 10 10]
[15  9 10 15 20]
[ 3 -1 -2 -5  0]
[ 54  20  24  50 100]


In [25]:
import numpy as np

vector_1 = np.random.randint(7),
vector_2 = np.random.randint (7)

print(np.dot(vector_1, vector_2))

[12]


In [30]:
import numpy as np

matrix_1 = np.random.randint(1, 11, size = (2,2))
matrix_2 = np.random.randint(1, 11, size = (2,3))

matrix_product = np.dot(matrix_1, matrix_2)


print("Матриця 1 (2x2):")
print(matrix_1)
print("\nМатриця 2 (2x3):")
print(matrix_2)
print("\nРезультат множення матриць:")
print(matrix_product)

Матриця 1 (2x2):
[[6 8]
 [3 7]]

Матриця 2 (2x3):
[[2 1 5]
 [4 7 7]]

Результат множення матриць:
[[44 62 86]
 [34 52 64]]


In [32]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a_inv = np.linalg.inv(a)
print(a_inv)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [33]:
import numpy as np

a = np.array([[1, 2, 3, 7],
              [4, 5, 6, 8],
              [7, 8, 9, 2]])

print(a)
b = a.T
print(b)

[[1 2 3 7]
 [4 5 6 8]
 [7 8 9 2]]
[[1 4 7]
 [2 5 8]
 [3 6 9]
 [7 8 2]]


In [34]:
import numpy as np


matrix = np.random.randint(1, 11, size=(3, 4))


vector = np.random.randint(1, 11, size=4)


result = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nРезультат перемноження:")
print(result)

Матриця 3x4:
[[ 4  4 10  9]
 [ 2  4  3  1]
 [ 7 10  2  8]]

Вектор:
[3 8 6 5]

Результат перемноження:
[149  61 153]


In [37]:
import numpy as np


matrix = np.random.randint(0, 1, size=(2, 3))


vector = np.random.randint(0, 1, size=3)


result = np.dot(matrix, vector)

print("Матриця 2x3:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nРезультат перемноження:")
print(result)

Матриця 2x3:
[[0 0 0]
 [0 0 0]]

Вектор:
[0 0 0]

Результат перемноження:
[0 0]


In [38]:
import numpy as np


matrix1 = np.random.randint(1, 11, size=(2, 2))


matrix2 = np.random.randint(1, 11, size=(2, 2))


elementwise_product = matrix1 * matrix2

print("Перша матриця 2x2:")
print(matrix1)
print("\nДруга матриця 2x2:")
print(matrix2)
print("\nПоелементне множення матриць:")
print(elementwise_product)

Перша матриця 2x2:
[[4 5]
 [2 5]]

Друга матриця 2x2:
[[ 6  6]
 [ 4 10]]

Поелементне множення матриць:
[[24 30]
 [ 8 50]]


In [40]:
import numpy as np


matrix1 = np.random.randint(1, 11, size=(2, 2))


matrix2 = np.random.randint(1, 11, size=(2, 2))


elementwise_product = np.dot(matrix1, matrix2)

print("Перша матриця 2x2:")
print(matrix1)
print("\nДруга матриця 2x2:")
print(matrix2)
print("\nДобуток:")
print(elementwise_product)

Перша матриця 2x2:
[[8 4]
 [1 4]]

Друга матриця 2x2:
[[6 5]
 [6 1]]

Добуток:
[[72 44]
 [30  9]]


In [41]:
import numpy as np

matrix1 = np.random.randint(1, 101, size=(5, 5))

sum_matrix = np.sum(matrix1, axis=1)
print(sum_matrix)

[226 202 271 229 246]


In [42]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(4, 4))

matrix2 = np.random.randint(1, 11, size=(4, 4))

difference_matrix = np.subtract(matrix1, matrix2)

print(difference_matrix)

[[-4  2  6  5]
 [ 5  0 -3  3]
 [-4 -5  2  1]
 [-2  3  1 -1]]


In [50]:
import numpy as np


matrix = np.random.rand(3, 3)


row_sums = np.sum(matrix, axis=1)

print("Матриця 3x3:")
print(matrix)
print("\nВектор-стовпчик, що містить суму елементів кожного рядка:")
print(row_sums)


Матриця 3x3:
[[0.34613806 0.40564563 0.07315766]
 [0.5062227  0.40653072 0.94663566]
 [0.9818209  0.96587789 0.98246831]]

Вектор-стовпчик, що містить суму елементів кожного рядка:
[0.82494135 1.85938909 2.9301671 ]


In [51]:
import numpy as np


matrix = np.random.randint(-10, 11, size=(3, 4))  


squared_matrix = matrix ** 2

print("Матриця 3x4:")
print(matrix)
print("\nМатриця з квадратами чисел:")
print(squared_matrix)


Матриця 3x4:
[[ 0  5 -2 -6]
 [-6  3  2 -2]
 [ 3  7 -3 -6]]

Матриця з квадратами чисел:
[[ 0 25  4 36]
 [36  9  4  4]
 [ 9 49  9 36]]


In [53]:
import numpy as np

vector = np.random.rand(1, 51)

squared_vector = vector ** 2

print(squared_vector)

[[6.00075272e-01 9.04112593e-05 2.42670512e-01 2.29517472e-02
  1.29582257e-01 3.58710692e-01 1.32098536e-01 3.14944580e-01
  1.99732962e-01 8.62907470e-01 4.69551378e-02 9.04123249e-01
  6.23452386e-01 2.50893776e-02 2.10404616e-02 6.14122500e-01
  8.88530559e-02 2.45950263e-01 1.20763484e-04 2.52400945e-01
  5.46671542e-01 3.36716121e-02 1.01976841e-01 1.07990298e-01
  7.57011982e-02 3.89960929e-01 4.60333231e-01 9.74085290e-01
  7.58280093e-02 1.62344004e-01 4.39065898e-03 5.52018052e-01
  1.14017153e-01 8.58925362e-01 3.56663199e-01 5.97722064e-02
  1.33759592e-04 1.31282060e-02 6.75150964e-02 3.75499760e-02
  1.44127633e-02 3.56158435e-01 3.03590156e-02 7.55174531e-01
  1.22217969e-01 3.00964537e-01 9.08591769e-01 4.58455982e-01
  8.54852355e-01 8.06683962e-01 1.63770277e-01]]
